[0.008s] Invoking command in '/home/pc/ros2_ws/build/robotics_interfaces': /usr/bin/cmake /home/pc/ros2_ws/src/robotics_interfaces -DCMAKE_INSTALL_PREFIX=/home/pc/ros2_ws/install/robotics_interfaces
[0.017s] -- Found ament_cmake: 1.3.11 (/opt/ros/humble/share/ament_cmake/cmake)
[0.108s] -- Found geometry_msgs: 4.8.0 (/opt/ros/humble/share/geometry_msgs/cmake)
[0.125s] -- Found rosidl_generator_c: 3.1.6 (/opt/ros/humble/share/rosidl_generator_c/cmake)
[0.127s] -- Found rosidl_adapter: 3.1.6 (/opt/ros/humble/share/rosidl_adapter/cmake)
[0.131s] -- Found rosidl_generator_cpp: 3.1.6 (/opt/ros/humble/share/rosidl_generator_cpp/cmake)
[0.137s] -- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
[0.146s] -- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
[0.170s] -- Found rosidl_default_generators: 1.2.0 (/opt/ros/humble/share/rosidl_default_generators/cmake)
[0.290s] [31mCMake Error at /opt/ros/humble/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:59 (message):
[0.290s]   execute_process(/usr/bin/python3 -m rosidl_adapter --package-name
[0.291s]   robotics_interfaces --arguments-file
[0.291s]   /home/pc/ros2_ws/build/robotics_interfaces/rosidl_adapter__arguments__robotics_interfaces.json
[0.291s]   --output-dir
[0.291s]   /home/pc/ros2_ws/build/robotics_interfaces/rosidl_adapter/robotics_interfaces
[0.291s]   --output-file
[0.291s]   /home/pc/ros2_ws/build/robotics_interfaces/rosidl_adapter/robotics_interfaces.idls)
[0.291s]   returned error code 1:
[0.291s] 
[0.291s]   Traceback (most recent call last):
[0.291s] 
[0.291s]     File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[0.291s]       return _run_code(code, main_globals, None,
[0.291s]     File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
[0.291s]       exec(code, run_globals)
[0.291s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__main__.py", line 19, in <module>
[0.291s]       sys.exit(main())
[0.291s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/main.py", line 53, in main
[0.291s]       abs_idl_file = convert_to_idl(
[0.291s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__init__.py", line 19, in convert_to_idl
[0.291s]       return convert_msg_to_idl(
[0.292s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/msg/__init__.py", line 28, in convert_msg_to_idl
[0.292s]       msg = parse_message_string(package_name, input_file.stem, content)
[0.292s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 544, in parse_message_string
[0.292s]       msg = MessageSpecification(pkg_name, msg_name, fields, constants)
[0.292s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 388, in __init__
[0.292s]       self.base_type = BaseType(
[0.292s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 205, in __init__
[0.292s]       raise InvalidResourceName(
[0.292s] 
[0.292s]   rosidl_adapter.parser.InvalidResourceName: 'trajectory' is an invalid
[0.292s]   message name.  It should have the pattern '^[A-Z][A-Za-z0-9]*$'
[0.292s] 
[0.292s] Call Stack (most recent call first):
[0.292s]   /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
[0.292s]   CMakeLists.txt:8 (rosidl_generate_interfaces)
[0.292s] 
[0.292s] [0m
[0.292s] -- Configuring incomplete, errors occurred!
[0.292s] See also "/home/pc/ros2_ws/build/robotics_interfaces/CMakeFiles/CMakeOutput.log".
[0.295s] Invoked command in '/home/pc/ros2_ws/build/robotics_interfaces' returned '1': /usr/bin/cmake /home/pc/ros2_ws/src/robotics_interfaces -DCMAKE_INSTALL_PREFIX=/home/pc/ros2_ws/install/robotics_interfaces
